version: '2.0'
services:
    transmission-openvpn:
        volumes:
            - /media/configs/transmission:/data/transmission-home
            - /mnt/hdd/incomplete:/data/incomplete
            - /mnt/hdd/complete:/downloads/transmission
        environment:
            - OPENVPN_PROVIDER=NORDVPN
            - OPENVPN_CONFIG=ca1020.nordvpn.com
            - OPENVPN_USERNAME=remydufour1510@gmail.com
            - OPENVPN_PASSWORD=SpliitNord59!,
            - WEBPROXY_ENABLED=false
            - LOCAL_NETWORK=192.168.1.0/24
        cap_add:
            - NET_ADMIN
        logging:
            driver: json-file
            options:
                max-size: 10m
        ports:
            - '9091:9091'
        image: transmission-openvpn
        restart: unless-stopped